### PR TITLE
Improved reference management to reduce memory leaks

### PR DESCRIPTION
**Pull request by rawnsley**
Fast room switching [exposes a number of issues](https://github.com/mozilla/hubs/issues/4832) with reference management that lead to large memory leaks and ultimately instability, particularly on mobile platforms.

One root cause was the use of APP level globals for variables that should really be bound to the scope of the room. Rather than make any radical changes, this PR continues to rely on `AudioSettingsSystem` to reset globals when the scene changes.

The _networkedEl_ NAF parameter is now reset to null in the few components where it was being assigned. There weren't any specific leaks associated with this, but it does confuse the process of tracking down actual leaks.

The most insidious leak was in the media-video component, where captured objects and captured functions appear to confound the garbage collector. Explicitly nulling out some of the references fixes the problem.

I've tried to keep the changes small and positive in and of themselves. I expect there are some edge cases where leaks can still happen, particularly where timing is a factor.

I will keep this PR in draft until I have tested the changes more widely on my own Hubs Cloud. All suggestions are welcome.

### CODE REVIEW

**Comment by vincentfretin** [comment]
FYI I did #5510 to fix disposing of the geometry and material of the simple-water component. There may be similar issues in other shader components, I didn't check.

**Comment by rawnsley** [comment]
The first test of this on my own Hubs Cloud code isn't very encouraging and I'm still seeing apparent memory leaks. I took the (now obvious) step of just filtering the snapshot results for "Detatched" objects and it looks like this:

Screenshot 2022-06-30 at 10 10 50

I'm already out of my depth on large web app development, but let me swim out a little further by saying that there should be no detached objects references after garbage collection.

**Comment by flankechen** [comment]
@rawnsley thanks for your report, by "It appears that at least one major leak was taken care of by @netpro2k during his recent refactoring. It was due to an attachment to event "camera-set-active" that was never removed." , did you mean this merge [New Entity Framework](https://github.com/mozilla/hubs/pull/5536) ? it seems hard to find "camera-set-active" related code.

**Comment by rawnsley** [comment]
@flankechen I think it was [this commit](https://github.com/mozilla/hubs/commit/5f8229a38c669a1b7053860eaf1aa5ee7e8e82c0#diff-7f28f4412d51a4907de1643b1af1acc1dc988c71a92e16ee7f69efb96cf7f189) that removes the event attachment.

**Comment by rawnsley** [comment]
I'm withdrawing this PR as the main branch has drifted significantly following the migration to bitECS, which should be inherently less leaky anyway.

**Pull request closed without merging**
