### PR TITLE
Test home page with browser stack

### PR DESCRIPTION
**Pull request by brianpeiris**
This is an experiment to test the home page in IE 11 using BrowserStack. The goal is to help test seldom-used browsers. In this case we add a basic test to load hubs.mozilla.com and ensure the home page renders in IE 11. The GitHub workflow added here runs on a weekly schedule.

### CODE REVIEW

**Review by keianhzo — COMMENTED** [review]
I don't see the action being fired. This should have fired already, right?

**Comment by brianpeiris** [comment]
Here's the list of runs for this branch: https://github.com/mozilla/hubs/actions/workflows/browser-stack.yml?query=branch%3Abrowser-stack-test

The latest run failed, but this is actually expected at the moment, since the app doesn't actually render in IE11 currently. That will have to be a separate fix.

**Comment by brianpeiris** [comment]
The home page will be fixed in IE11 with this change: https://github.com/mozilla/reticulum/pull/589
Though we'll have to update this test to detect the "unsupported" message instead of the "create room" button.

**Review by keianhzo — APPROVED** [review]
Ok, I was expecting it as part of the PR actions but it makes sense that it's out of it.

**Pull request merged**
