### PR TITLE
Rename LICENSE to README LICENSE

### PR DESCRIPTION
**Pull request by AvionZz**

### CODE REVIEW

**Comment by AvionZz** [comment]
(i)

**Comment by gfodor** [comment]
Hi there @AvionZz thank you for the PR! Can you explain a bit about why you suggest we rename this file?

**Comment by AvionZz** [comment]
(I)

**Comment by AvionZz** [comment]
@gfodor  .. I just want my life back.

**Comment by gfodor** [comment]
not sure about this one. closing for now.

**Pull request closed without merging**
