### PR TITLE
internationalize You and Preferences item in More menu

### PR DESCRIPTION
**Pull request by vincentfretin**

### CODE REVIEW

**Comment by vincentfretin** [comment]
I fixed 3 i18n issues, one in the invite popover for "Enter code on hubs.link" and 2 in the More menu, the "You" and the "Preferences". Here how it looks like in French now:
Capture d’écran de 2022-01-08 20-10-09
Capture d’écran de 2022-01-08 20-14-29

**Review by matthewbcool — APPROVED** [review]
lgtm. One possible change we can consider is removing  "You" and the parens from the more menu. making a note here that these correspond to  `"more-menu.you"` and "more-`menu.you-signed-in-as"`

**Comment by vincentfretin** [comment]
I think it's good you know the email you are connected with. You may connect with different mails, personal or one from your company.

**Comment by matthewbcool** [comment]
agreed, I'm proposing we remove the "()" and "you". Can be done here or in a future PR.

**Pull request merged**
