### PR TITLE
Scale cursor size with player size

### PR DESCRIPTION
**Pull request by mquander**
This is an easy improvement to the status quo and makes the cursor look and feel reasonable at different scales, although the "shine" of the cursor on a media object still looks a little funny if you get really small.

It seems like it works fine if we just leave the physics body of the cursor the original size.

### CODE REVIEW

**Comment by gfodor** [comment]
Oh, when we were chatting earlier my suggestion was to also scale the cursor based upon distance to ensure it has a fixed size in your visual field (technically steradians)

**Comment by mquander** [comment]
I see, I didn't know we desired that effect -- I am not quite sure how "physical" we want the cursor to seem.

**Comment by gfodor** [comment]
Here's a PR that does what I was thinking (and speeds things up too) https://github.com/mozilla/hubs/pull/757

**Comment by gfodor** [comment]
ended up merging #757

**Pull request closed without merging**
