### PR TITLE
[WIP] Fixes #307: Added HashRouter in index.js

### LINKED ISSUE #307: modals should be accessible via URL
1. load https://hubs.mozilla.com/
2. scroll to footer at the bottom of the page
3. on desktop, hover over the first three links and notice the URL tooltips are `https://hubs.mozilla.com/#` (from `a[href="#"]`)

screen shot 2018-04-25 at 8 59 02 pm

ideally, at these URLs, the respective modals could be opened (or links be opened):

- `/contact` - **Join the Conversation**
- `/subscribe` - **Get Updates**
- `/report` - **Report Issues**
- `/terms` - **Terms of Use**
- `/privacy` - **Privacy Notice**

hashes (e.g., `#contact`) are possible but would not be preferable, as hashes don't appear in server logs/analytics (unless manually handling them in client-side JS).

### PR DESCRIPTION
**Pull request by suhailsinghbains**
Fixes #307: Added HashRouter in index.js
I was hoping if I could do partial work for now and do rest after a review :)

### CODE REVIEW

**Comment by gfodor** [comment]
Looks like a good start! I'd suggest renaming the variable from `test` to `router`, and please make sure linter passes.

**Comment by suhailsinghbains** [comment]
Hi @gfodor 
Please review my PR.
Thanks

**Comment by gfodor** [comment]
thanks for the update! this is looking good, do you think you can also update the links to drive the routes?

**Comment by suhailsinghbains** [comment]
Yes, sure.

**Comment by brianpeiris** [comment]
Sorry this took so long!

**Pull request merged**
