### PR TITLE
fix button color on default theme settings

### PR DESCRIPTION
**Pull request by yakyouk**
- fix action button color: when user preference theme is 'default', the action button and action button highlight theme colors are not correctly applied on action buttons. Note that theme logic is duplicated in `utils/themes.json` and `react-components/styles/themes.js`. I did not find a good way to prevent this but I added a mention of this in both files.
- fixes for `webpack.config.json`:
  - fix localDev themes: themes JSON was not parsed
  - ~~fix remoteDev themes: moved theme from `appConfig.themes` to `appConfig.theme.themes`~~ (already fixed in master)
  - add `/link`, `/scenes` and `/avatars` paths for development
  - add `basis_transcoder.worker.js` to `.prettierignore` to prevent prettifying with `npm run prettier`

┆Issue is synchronized with this [Jira Task](https://mozilla-hub.atlassian.net/browse/HUBS-792)

### CODE REVIEW

**Review by nayeem01 — APPROVED** [review]

**Review by matthewbcool — APPROVED** [review]

**Comment by takahirox** [comment]
Unfortunately this PR has conflicting. Would you resolve them (unless the changes are outdated)?

@matthewbcool Let me know if you are not sure how to merge and deploy.

**Comment by yakyouk** [comment]
Updated, some of the theme fixes were already in master, some were still missing.

The PR addresses multiple different issues, lmk if I should split it into different PRs for each issue:
- fix theme (local dev and deployed client)
- add /link, /scene, /avatars paths for local dev
- add `basis_transcoder.worker.js` to `.prettierignore` to prevent prettifying with `npm run prettier`

**Comment by takahirox** [comment]
@yakyouk Thanks for the update!

@matthewbcool Do you mind if reviewing again?

**Comment by brianpeiris** [comment]
This looked good to me in general, but I decided to try to refactor and reuse the theming logic a bit more. I made #5651, which builds on top of this PR.

**Comment by yakyouk** [comment]
closed in favor of https://github.com/mozilla/hubs/pull/5651

**Pull request closed without merging**
