### PR TITLE
Media wording adjusted

### PR DESCRIPTION
**Pull request by SparshKat**
Issue #1487 has been fixed by doing some basic changes to the translations.json file

### CODE REVIEW

**Comment by gfodor** [comment]
lgtm!

**Comment by SparshKat** [comment]
Hope its good enough to be merged !

**Comment by SparshKat** [comment]
Great !

**Comment by SparshKat** [comment]
Is there something else that i need to do  to the following PR or are there few other things that one needs to get it merged ?

**Comment by johnshaughnessy** [comment]
Thanks @SparshKat ! I'll merge this today.

**Pull request merged**
