### PR TITLE
Making the chat box easier to spot

### PR DESCRIPTION
**Pull request by Mordax**
This is in reference to PR #862 - screwed up my branch by accidentally merging it.

### CODE REVIEW

**Comment by gfodor** [comment]
Hey Mordox, I'm working on updating our chat box design now. After trying some other stylings in addition to the ones you have suggested I landed on adjusting the opacity values. I'll CC you on the PR when it is ready.

**Comment by Mordax** [comment]
@gfodor Alright. In the meantime, mind if I investigate private messaging and chat history?

**Comment by gfodor** [comment]
Sure! PR is here:

https://github.com/mozilla/hubs/pull/896

As mentioned on the github issue, the main thing to start with regards to history is a working prototype of a design that works well on desktop + mobile and does not get in the way of the main in-game view. If we had a working prototype of a design, we could add the actual functionality of intra-session history pretty easily.

I'm not sure what we'd want to do for private messaging. Its not something we've talked about much internally, and as I mentioned in the ticket one big problem right now is you'd have no way to respond privately from within VR.

Thanks for offering to help!

**Comment by gfodor** [comment]
this is going out now, hope this helps: https://github.com/mozilla/hubs/pull/896

**Pull request closed without merging**
