### PR TITLE
Unhide users from the presence list

### PR DESCRIPTION
**Pull request by johnshaughnessy**
Resolves https://github.com/mozilla/hubs/issues/1259

### CODE REVIEW

**Comment by gfodor** [comment]
Unfortunately I think this design needs to be revisited, since we need a similar mechanic to also allow kicking and muting from the presence list. My guess is we will need some kind of menu you can expect on the items in the presence list to reveal actions you can take on that person's avatar. (Though I don't mind us shipping this as a v1)

Also, how does this deal with objects the user has spawned?

**Comment by johnshaughnessy** [comment]
Regarding objects the user has spawned:
Alice spawns a duck.
Bob hides Alice. The duck disappears because Alice owns it.
Bob unhides Alice. The duck reappears because it is part of Alice's "full sync" message (as long as Alice still owns the duck).


Likewise, Alice sees Bob's objects come back because Bob also sends Alice a "full sync".

If Charlie takes ownership of Alice's duck while Alice is hidden from Bob, then Bob never sees the duck. This is how hiding currently works in production. If Charlie deletes the duck, Bob will receive this message in the console:
image

**Comment by gfodor** [comment]
please hold off on merging this, i'm going to work on a modal that lets users perform actions on others via the presence list, and will include 'unhide' as a verb (extracting the relevant bits from this PR)

**Comment by gfodor** [comment]
Closing in favor of https://github.com/mozilla/hubs/pull/1310

**Pull request closed without merging**
